require 'hoe'
require './lib/coolcats/version.rb'

###
# hack/ quick fix for broken intuit_values - overwrite with dummy
class Hoe
  def intuit_values( input ); end
end



Hoe.spec 'coolcats' do

  self.version = Pixelart::Module::Coolcats::VERSION

  self.summary = "coolcats - generate your own 24×24 pixel cat images (off-blockchain) from text attributes (via built-in spritesheet); incl. 2x/4x/8x zoom for bigger sizes and more"
  self.description = summary

  self.urls    = { home: 'https://github.com/profilepic/text-to-image' }

  self.author  = 'Gerald Bauer'
  self.email   = 'wwwmake@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
    ['artfactory', '>= 0.2.0'],
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.3'
  }

end
